### ISSUE TITLE
Question issue about running in parallel

### ISSUE THREAD

**Issue by calvario31** [RankWeis/uppercut#108]
Hi man

I'm uploading a karate log for this scenario. I have a feeling is running multiple times/parallel. However I Haven't enabled that option
Only happens when clicking on play button on uppercut plugin

![Image](https://github.com/user-attachments/assets/29d99841-ac83-4c88-a71e-7e92d09bc803)

this is my karate-config
```
function fn() {
    var config = {
        mainUrl: "https://dummyjson.com/auth"
    }

    const result = karate.callSingle('classpath:dummyjson/Login.feature')
    config.auth = {"Authorization": `Bearer ${result.token}`}

    return config;
}
```

and this my login.feature

```
Feature: Login

  Background: Precondition
    Given url "https://dummyjson.com"

  Scenario: Login
    * def loginPayload =
    """
    {
      "username": "emilys",
      "password": "emilyspass",
      "expiresInMins": 30
    }
    """

    Given path "auth", "login"
    * request loginPayload
    When method POST
    Then status 200
    * def token = response.accessToken

```

[karate.log](https://github.com/user-attachments/files/18568554/karate.log)

**Comment by calvario31** [comment]
Is this something new? 

![Image](https://github.com/user-attachments/assets/b7e1f7bd-f889-48fe-8c2d-ce328511c700)

![Image](https://github.com/user-attachments/assets/c880a429-d049-4931-98bf-f9ded408423b)

**Comment by RankWeis** [comment]
Not new, this should have been there since the initial version. I'm surprised I didn't make it configurable, I'd always meant to. I didn't know what to set the default at, whether it should be just 1 or some higher number. I was waiting for feedback to tell me 5 was bad :) So now I know, I'll default it to 1 and make it configurable

**Comment by calvario31** [comment]
oh ok, yes I believe 1 as default is the way to go and make it configurable

**Comment by RankWeis** [comment]
Should be uploaded, just waiting on jetbrains approval which is really fast these days. Probably ten minutes or so, but I’m off to bed now so I will check in in the morning!

**Comment by calvario31** [comment]
hi man seems parallel is gone

however still running twice

this is the logs when I use runner class

[karate.log](https://github.com/user-attachments/files/18576655/karate.log)

and this is the same scenario running with uppercut play button

[karate.log](https://github.com/user-attachments/files/18576662/karate.log)

if you search for `POST https://dummyjson.com/auth/login` on the log using runner will appear one time and uppercut twice

**Comment by RankWeis** [comment]
I see, thanks and sorry. Looking into it.

**Comment by calvario31** [comment]
believe can be tied with this old issue https://github.com/RankWeis/uppercut/issues/42

**Comment by RankWeis** [comment]
That's the one I actually fixed I believe. That was because when you compile code the feature files end up in your classpath as well as your main directory, and it would find both and run them, now I ignore the classpath file and just run the requested file.

To clarify, here you're running login.feature with the play button? Because then I think this might make sense unless I'm misunderstanding something. But in your karate-config you tell it to run login.feature, so it runs login.feature once, and then clicking play it also runs login.feature. So once from your karate-config, once from you actually telling it what to run. 

Can you send me the command you're running with the runner class so I can compare?

**Comment by calvario31** [comment]
expected flow:
login -> products

actual flow, I don't clearly understand  the order but I believe it is:
login -> products 
login -> products
```
package dummyjson.products;

import com.intuit.karate.junit5.Karate;

class ProductsRunner {
    
    @Karate.Test
    Karate testProducts() {
        return Karate.run("products").relativeTo(getClass());
    }    

}
```

**Comment by RankWeis** [comment]
Thanks, I can reproduce now. Will look into it today.

**Comment by RankWeis** [comment]
I'm having a little trouble tracking this one down and it's gotten busy, but this is still on my mind and efforts.

**Comment by RankWeis** [comment]
PHEW I found it. Releasing very soon.

**Comment by RankWeis** [comment]
This should be fixed in v2.3.0, now available on intellij

**Comment by calvario31** [comment]
thanks will check and let you know

**Comment by calvario31** [comment]
Im seeing some weird behaviour

Im running get single product tests. However on the results it says Login.feature

![Image](https://github.com/user-attachments/assets/af9806e7-8bf4-46de-8cf2-226ce5b4efb3)

Also logs are lack of information 

```
13:11:17.699 [main] INFO  com.intuit.karate.Suite - backed up existing 'target/karate-reports' dir to: target/karate-reports_1738951877697
13:11:17.705 [main] INFO  ROOT - FeatureFileName: dummyjson/products/Products.feature, START
13:11:17.715 [main] INFO  c.intuit.karate.core.FeatureRuntime - found scenario at line: 7
13:11:18.095 [main] INFO  com.intuit.karate - >> lock acquired, begin callSingle: classpath:dummyjson/Login.feature
13:11:18.097 [main] INFO  ROOT - FeatureFileName: dummyjson/Login.feature, START
13:11:18.102 [main] INFO  com.intuit.karate - Scenario name: Login, featureFileName: dummyjson/Login.feature, id 1324031466, START
13:11:18.686 [main] INFO  com.intuit.karate - Scenario name: Login, featureFileName: dummyjson/Login.feature, id 1324031466, FINISH
13:11:18.686 [main] INFO  ROOT - FeatureFileName: dummyjson/Login.feature, FINISH
13:11:18.686 [main] INFO  com.intuit.karate - << lock released, cached callSingle: classpath:dummyjson/Login.feature
13:11:18.695 [main] INFO  com.intuit.karate - Scenario name: Get Product, featureFileName: dummyjson/products/Products.feature, id 1500351330, START
13:11:19.047 [main] INFO  com.intuit.karate - Scenario name: Get Product, featureFileName: dummyjson/products/Products.feature, id 1500351330, FINISH
13:11:19.047 [main] INFO  ROOT - FeatureFileName: dummyjson/products/Products.feature, FINISH
13:11:19.356 [main] INFO  com.intuit.karate.Suite - <<pass>> feature 1 of 1 (0 remaining) classpath:dummyjson/products/Products.feature

```

This is the project im using maybe is easier to reproduce that way

https://drive.google.com/drive/folders/182-crVarxE6sPH_InK_c50bN5AzJEOsd?usp=sharing

**Comment by RankWeis** [comment]
Yeah this is a known issue I'm trying to figure out, it's if you have a test run in the karate-config.js, that test never sends an "I'm done" marker, so I can't tell if it succeeded or failed. I'll look more into it, but that behaviors been there for a while.

**Comment by RankWeis** [comment]
I was overcomplicating things, that was easier than I thought. I'm building a fix right now.

**Comment by RankWeis** [comment]
Fixed in 2.3.1

**Comment by calvario31** [comment]
can't be sure if it fixed since it does not show all the logs now
```
20:10:02.447 [main] INFO  com.intuit.karate.Suite - backed up existing 'target/karate-reports' dir to: target/karate-reports_1739236202445
20:10:02.451 [main] INFO  ROOT - FeatureFileName: dummyjson/products/Products.feature, START
20:10:02.461 [main] INFO  c.intuit.karate.core.FeatureRuntime - found scenario at line: 7
20:10:02.887 [main] INFO  com.intuit.karate - >> lock acquired, begin callSingle: classpath:dummyjson/Login.feature
20:10:02.889 [main] INFO  ROOT - FeatureFileName: dummyjson/Login.feature, START
20:10:02.894 [main] INFO  com.intuit.karate - Scenario name: Login, featureFileName: dummyjson/Login.feature, id 110824674, START
20:10:03.502 [main] INFO  com.intuit.karate - Scenario name: Login, featureFileName: dummyjson/Login.feature, id 110824674, FINISH
20:10:03.503 [main] INFO  ROOT - FeatureFileName: dummyjson/Login.feature, FINISH
20:10:03.503 [main] INFO  com.intuit.karate - << lock released, cached callSingle: classpath:dummyjson/Login.feature
20:10:03.513 [main] INFO  com.intuit.karate - Scenario name: Get Product, featureFileName: dummyjson/products/Products.feature, id 404925794, START
20:10:03.867 [main] INFO  com.intuit.karate - Scenario name: Get Product, featureFileName: dummyjson/products/Products.feature, id 404925794, FINISH
20:10:03.867 [main] INFO  ROOT - FeatureFileName: dummyjson/products/Products.feature, FINISH
20:10:04.152 [main] INFO  com.intuit.karate.Suite - <<pass>> feature 1 of 1 (0 remaining) classpath:dummyjson/products/Products.feature
```

**Comment by RankWeis** [comment]
You can look at the karate.log to double check but yeah I agree this isn't the best experience. Karate isn't behaving consistently from what I can tell so some items get finishing tags of a certain kind and some don't, so if I look at the earlier finishing tags I can get all the tests finished , if I look at the later finishing tag I don't finish karate-config.js tests but I get more logs. I'll have to think about how to solve this, probably this weekend

**Comment by calvario31** [comment]
In fact the code posted was from karate.log

![Image](https://github.com/user-attachments/assets/b78f4e13-e72a-4c3d-8305-a6551ee89b96)

**Comment by RankWeis** [comment]
Oh man you just helped me solve this bug and a mystery that's been plaguing me since the beginning. Should have a build out shortly if you could test it, then I can send it out

**Comment by RankWeis** [comment]
Not so shortly that you should wait on it tonight, just sooner than I expected.

**Comment by calvario31** [comment]
may I ask which was the issue and the solution? hehe

**Comment by RankWeis** [comment]
I've been having to override the default logging this whole time and I never knew why, I felt like I shouldn't have to interrupt other people's logs just to get mine where I wanted. And then when I did override people's logs, they were still there. 

Well it turns out that the *wrong* test that was running, the one that was running twice, was the one populating all the original logs, and my logging appender was just appending some additional logs that I needed. So you showed me karate.log and I realized that now that the second test isn't running, my overrides of people's logs doesn't need to be there any more, and I feel a lot more comfortable with that.

**Comment by calvario31** [comment]
oh cool that you figure it out with my help

**Comment by calvario31** [comment]
hi man, any updates?

**Comment by RankWeis** [comment]
Yeah I think it’s done but I’m trying to add some debugging options which is doing my head in so maybe I’ll just release in its current form and figure out the debugging stuff later. Need to test to make sure I didn’t break anything

**Comment by RankWeis** [comment]
These should be fixed in this attached release, had some problems with the build system but that seems fixed now. You also get a nice place in the README! But I'm probably releasing this tomorrow, just wanted to give you a heads up if you want to prlay around with it first, thanks!

[uppercut-2.3.2.zip](https://github.com/user-attachments/files/18833949/uppercut-2.3.2.zip)

**Comment by calvario31** [comment]
Hi man thanks for adding me to the README

I installed manually your 2.3.2 file but still cannot see the whole logs on the console nor the karate.logs

this is karate.logs
```
20:10:02.447 [main] INFO  com.intuit.karate.Suite - backed up existing 'target/karate-reports' dir to: target/karate-reports_1739236202445
20:10:02.451 [main] INFO  ROOT - FeatureFileName: dummyjson/products/Products.feature, START
20:10:02.461 [main] INFO  c.intuit.karate.core.FeatureRuntime - found scenario at line: 7
20:10:02.887 [main] INFO  com.intuit.karate - >> lock acquired, begin callSingle: classpath:dummyjson/Login.feature
20:10:02.889 [main] INFO  ROOT - FeatureFileName: dummyjson/Login.feature, START
20:10:02.894 [main] INFO  com.intuit.karate - Scenario name: Login, featureFileName: dummyjson/Login.feature, id 110824674, START
20:10:03.502 [main] INFO  com.intuit.karate - Scenario name: Login, featureFileName: dummyjson/Login.feature, id 110824674, FINISH
20:10:03.503 [main] INFO  ROOT - FeatureFileName: dummyjson/Login.feature, FINISH
20:10:03.503 [main] INFO  com.intuit.karate - << lock released, cached callSingle: classpath:dummyjson/Login.feature
20:10:03.513 [main] INFO  com.intuit.karate - Scenario name: Get Product, featureFileName: dummyjson/products/Products.feature, id 404925794, START
20:10:03.867 [main] INFO  com.intuit.karate - Scenario name: Get Product, featureFileName: dummyjson/products/Products.feature, id 404925794, FINISH
20:10:03.867 [main] INFO  ROOT - FeatureFileName: dummyjson/products/Products.feature, FINISH
20:10:04.152 [main] INFO  com.intuit.karate.Suite - <<pass>> feature 1 of 1 (0 remaining) classpath:dummyjson/products/Products.feature
21:50:12.222 [main] INFO  com.intuit.karate.Suite - backed up existing 'target/karate-reports' dir to: target/karate-reports_1739847012221
21:50:12.227 [main] INFO  c.r.u.testrunner.KarateTestRunner - FeatureFileName: dummyjson/products/Products.feature, START
21:50:12.236 [main] INFO  c.intuit.karate.core.FeatureRuntime - found scenario at line: 7
21:50:12.691 [main] INFO  com.intuit.karate - >> lock acquired, begin callSingle: classpath:dummyjson/Login.feature
21:50:12.695 [main] INFO  c.r.u.testrunner.KarateTestRunner - FeatureFileName: dummyjson/Login.feature, START
21:50:12.699 [main] INFO  com.intuit.karate - Scenario name: Login, featureFileName: dummyjson/Login.feature, id 2091904368, START
21:50:13.660 [main] INFO  com.intuit.karate - Scenario name: Login, featureFileName: dummyjson/Login.feature, id 2091904368, FINISH
21:50:13.660 [main] INFO  c.r.u.testrunner.KarateTestRunner - FeatureFileName: dummyjson/Login.feature, FINISH
21:50:13.660 [main] INFO  com.intuit.karate - << lock released, cached callSingle: classpath:dummyjson/Login.feature
21:50:13.669 [main] INFO  com.intuit.karate - Scenario name: Get Product, featureFileName: dummyjson/products/Products.feature, id 50061526, START
21:50:14.024 [main] INFO  com.intuit.karate - Scenario name: Get Product, featureFileName: dummyjson/products/Products.feature, id 50061526, FINISH
21:50:14.024 [main] INFO  c.r.u.testrunner.KarateTestRunner - FeatureFileName: dummyjson/products/Products.feature, FINISH
21:50:14.300 [main] INFO  com.intuit.karate.Suite - <<pass>> feature 1 of 1 (0 remaining) classpath:dummyjson/products/Products.feature

```

**Comment by calvario31** [comment]
yikes seems my bad. You are right im only checking INFO level, with debug it show all the info as usual

**Comment by calvario31** [comment]
seems this can be closed, tyvm and sorry for the confusion!

**Comment by RankWeis** [comment]
Awesome, this should be resolved in now released v2.3.2
