### ISSUE TITLE
Log issue arises again

### ISSUE THREAD

**Issue by calvario-31** [RankWeis/uppercut#46]
Hi man, 
was testing v1.22 (from IntelliJ marketplace) 

Sadly seems the log issue appeared again

```
0:16:44,361 |-INFO in ch.qos.logback.classic.util.ContextInitializer@64d2d351 - Trying to configure with ch.qos.logback.classic.util.DefaultJoranConfigurator
00:16:44,361 |-INFO in ch.qos.logback.classic.util.ContextInitializer@64d2d351 - Constructed configurator of type class ch.qos.logback.classic.util.DefaultJoranConfigurator
00:16:44,366 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback-test.xml] at [file:/Users/calvario31/Documents/Projects/karate/karate-test/target/test-classes/logback-test.xml]
00:16:44,367 |-WARN in ch.qos.logback.classic.util.DefaultJoranConfigurator@1b68b9a4 - Resource [logback-test.xml] occurs multiple times on the classpath.
00:16:44,367 |-WARN in ch.qos.logback.classic.util.DefaultJoranConfigurator@1b68b9a4 - Resource [logback-test.xml] occurs at [file:/Users/calvario31/Documents/Projects/karate/karate-test/target/test-classes/logback-test.xml]
00:16:44,367 |-WARN in ch.qos.logback.classic.util.DefaultJoranConfigurator@1b68b9a4 - Resource [logback-test.xml] occurs at [jar:file:/Users/calvario31/Library/Application%20Support/JetBrains/IdeaIC2024.3/plugins/uppercut/lib/uppercut-1.2.2.jar!/logback-test.xml]
```

If I run using the karate runner the logs seems fine
![image](https://github.com/user-attachments/assets/6896c907-4e12-42e5-9098-ef8ce013b6d3)

![image](https://github.com/user-attachments/assets/121d246c-11cc-4f9d-a83c-15bcc5fdb425)

The issue is when pressing play on the Scenario
![image](https://github.com/user-attachments/assets/b1c9bf63-2885-4890-9f2f-a8e45a4d63ec)

![image](https://github.com/user-attachments/assets/7c4e7aa8-f997-436b-bb69-227c2adf90be)

Please let me know if you need more info or if Im doing something wrong

It works if I delete my local `logback-test.xml` so seems is related to the duplication

I believe this problem reappeared when I updated my intellij version to the latest. Im using: 
Build #IC-243.21565.193, built on November 12, 2024

**Comment by RankWeis** [comment]
Any chance you can show me your logback-test.xml? I'm working on a fix right now but am not fully able to reproduce the issue

**Comment by RankWeis** [comment]
[uppercut-1.2.3-base.jar.zip](https://github.com/user-attachments/files/17771274/uppercut-1.2.3-base.jar.zip)

I believe this should fix the issue, I'm sending it out tonight but if you have time and experience any issues with it please let me know. This should address this and #47

**Comment by RankWeis** [comment]
Actually the fix was approved and is on live intelliJ, please check it out if you can!

**Comment by calvario-31** [comment]
Hello,

Im using template/quickstart logback-test.xml

this is the code 

```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>

    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
        </encoder>
    </appender>

    <appender name="FILE" class="ch.qos.logback.core.FileAppender">
        <file>src/test/resources/karate.log</file>
        <encoder>
            <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
        </encoder>
    </appender>

    <logger name="com.intuit" level="DEBUG"/>

    <root level="info">
        <appender-ref ref="STDOUT"/>
        <appender-ref ref="FILE"/>
    </root>

</configuration>
```

Was testing 1.2.3 the error of duplicating does not appear
However, the log still not populate. I think the critical part is on the report we cannot see the info of the request

![image](https://github.com/user-attachments/assets/6eb06b43-f800-4d02-b90a-e522aad67458)

**Comment by RankWeis** [comment]
Ah, I see. I'm not entirely sure how the report is generated, but it does clearly use the logs from karate.log. Can you set the log level of the root level to 'debug' and see if that is better? It's a little noisy but may get you halfway there. Getting the report to generate is something I spent a bit of time on in my first pass developing this and I was unable to get it to be as good as running with the test suite. I'll spend some more time on it and see what I can do.

**Comment by calvario-31** [comment]
I believe the report takes the info directly from karate.log 
Have tried to update root level to debug but still the same result

**Comment by RankWeis** [comment]
Thanks for your patience. I do think I've got it working this time. Release should be out relatively soon but if you want the sneak peek it's here, otherwise please wait just a bit and we should have everything good from intellij's store. Thank you so much for your feedback as well, I only really know my own use cases for the plugin and it's hard to tell if other people are having issues without it!

[uppercut-1.2.4-base.jar.zip](https://github.com/user-attachments/files/17778538/uppercut-1.2.4-base.jar.zip)

**Comment by calvario-31** [comment]
thanks man just tested it and this issue is fixed with that version
